version: '3'

services: 
  frontend:
    build:
      context: .
      dockerfile: FrontendDockerFile

  backend:
    build:
      context: .
      dockerfile: BackendDockerFile
    environment:
      - REDIS=host.docker.internal
      - DB_USERNAME=user
      - DB_PASSWORD=myPassword
      - DB_HOST=host.docker.internal
    depends_on:
      - db
      - redis

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - frontend
      - backend

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=myPassword
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  redis-data:
  db-data:
