version: '3'

services: 
  frontend:
    build:
      context: .
      dockerfile: FrontendDockerFile

  backend:
    build:
      context: .
      dockerfile: BackendDockerFile
    environment:
      - REDIS=host.docker.internal
      - DB_USERNAME=user
      - DB_PASSWORD=myPassword
      - DB_HOST=host.docker.internal

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=myPassword
